name: growy_admin_panel
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0 


  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  iconly: ^1.0.1
  card_swiper: ^2.0.4
  fancy_shimmer_image: ^2.0.2
  flutter_staggered_grid_view: ^0.6.2
  badges: ^2.0.3
  dotted_border: ^2.0.0+2
  image_picker: ^0.8.6
  flutter_spinkit: ^5.1.0
  uuid: ^3.0.6
  fluttertoast: ^8.1.1
  
  flutter_locales: ^2.0.2
  #FireBase
  firebase: ^9.0.3
  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.4
  firebase_storage: ^11.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/groceries.png
    - assets/images/warning-sign.png
  

  